@echo off
echo Starting MindMate Development Servers...

echo Starting Backend Server...
start "Backend Server" cmd /k "cd server && node index.js"

echo Waiting for backend to start...
timeout /t 3 /nobreak > nul

echo Starting Frontend Server...
start "Frontend Server" cmd /k "cd client && npm start"

echo Both servers are starting...
echo Backend: http://localhost:5000
echo Frontend: http://localhost:3000
pause
